version: '3.8'
services:
  linux:
    image: ataylorregistry.azurecr.io/ado-windows-agent:1.0
    deploy: 
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      placement: 
        constraints: 
          - node.role != manager
          - node.labels.os == windows
    dns:
      - 8.8.8.8
      - 8.8.4.4
