version: '3.8'
services:
  linux:
    image: ataylorregistry.azurecr.io/ado-linux-agent:1.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy: 
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      placement: 
        constraints: 
          - node.role != manager
          - node.labels.os == linux
    dns:
      - 8.8.8.8
      - 8.8.4.4
