#!/bin/bash
echo "nameserver 8.8.8.8" > /etc/resolv.conf

set -e

source ./env.sh

export VSO_AGENT_IGNORE=_,ADO_AGENT_LINUX2_SERVICE_PORT,\
  ADO_AGENT_LINUX2_PORT_443_TCP_PORT,\
  ADO_AGENT_LINUX2_PORT_443_TCP_PROTO,\
  ADO_AGENT_LINUX2_SERVICE_HOSTInteractiveSession,\
  ADO_AGENT_LINUX2_PORT,\
  ADO_AGENT_LINUX2_PORT_443_TCP,\
  ADO_AGENT_LINUX2_PORT_443_TCP_ADDR,\
  ADO_AGENT_LINUX_PORT_443_TCP_PROTO,\
  ADO_AGENT_LINUX_SERVICE_HOST,\
  ADO_AGENT_LINUX_SERVICE_PORT,\
  ADO_AGENT_LINUX_PORT_443_TCP_PORT,\
  ADO_AGENT_LINUX_PORT,\
  ADO_AGENT_LINUX_PORT_443_TCP,\
  ADO_AGENT_LINUX_PORT_443_TCP_ADDR,\
  AZP_TOKEN,\
  AZP_WORK,\
  AZP_POOL,\
  HOSTNAME,\
  KUBERNETES_SERVICE_HOST,\
  KUBERNETES_SERVICE_PORT,\
  KUBERNETES_SERVICE_PORT_HTTPS,\
  KUBERNETES_PORT,\
  KUBERNETES_PORT_443_TCP,\
  KUBERNETES_PORT_443_TCP_ADDR,\
  KUBERNETES_PORT_443_TCP_PORT,\
  KUBERNETES_PORT_443_TCP_PROTO,\
  DEBIAN_FRONTEND,\
  HOME,\
  InteractiveSession,\
  MAIL,\
  OLDPWD,\
  PATH,\
  PWD,\
  VSTS_AGENT,\
  VSTS_ACCOUNT,\
  VSTS_TOKEN_FILE,\
  VSTS_TOKEN,\
  VSTS_POOL,\
  VSTS_WORK,\
  VSO_AGENT_IGNORE


if [ -n "$VSTS_AGENT_IGNORE" ]; then
  export VSO_AGENT_IGNORE=$VSO_AGENT_IGNORE,VSTS_AGENT_IGNORE,$VSTS_AGENT_IGNORE
fi

touch /vsts/.configure
rm -rf /vsts/agent
mkdir /vsts/agent

cd /vsts/bin

./Agent.Listener configure --unattended \
  --agent "$(hostname)" \
  --url "$AZP_ADO_URL" \
  --auth PAT \
  --token "$AZP_TOKEN" \
  --pool "$AZP_POOL" \
  --work "$AZP_WORK" \
  --acceptTeeEula \
  --replace & wait $!

./Agent.Listener run --once & wait $!
